resources:
  - url: http://127.0.0.1:5000/energy-ratio-donut-card.js
    type: module
views:
  - cards:
      - type: custom:energy-ratio-donut-card
        name: Energy ratio donut card Development
        entity: sun.sun
        test_gui: true
